create table car (
	id 	BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price NUMERIC(19, 2) NOT NULL
);

insert into car (make, model, price) values ('Maserati', 'Spyder', 9579.47);
insert into car (make, model, price) values ('Dodge', 'Ram 3500 Club', 9466.83);
insert into car (make, model, price) values ('Hyundai', 'XG350', 15400.54);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 13227.56);
insert into car (make, model, price) values ('Cadillac', 'XLR', 11450.57);
insert into car (make, model, price) values ('Audi', 'Q5', 6047.78);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', 15360.77);
insert into car (make, model, price) values ('Ford', 'Escort', 15909.72);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 13063.79);
insert into car (make, model, price) values ('Suzuki', 'Daewoo Lacetti', 10491.42);
insert into car (make, model, price) values ('Pontiac', 'Vibe', 10215.55);
insert into car (make, model, price) values ('Mazda', 'RX-7', 14824.98);
insert into car (make, model, price) values ('Plymouth', 'Voyager', 7421.39);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 2009.76);
insert into car (make, model, price) values ('Volkswagen', 'Rabbit', 18802.42);
insert into car (make, model, price) values ('Chrysler', 'LHS', 14440.24);
insert into car (make, model, price) values ('Lexus', 'LX', 7525.14);
insert into car (make, model, price) values ('Ford', 'Expedition EL', 12708.92);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 16248.27);
insert into car (make, model, price) values ('Toyota', 'T100', 9846.13);
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', 3451.4);
insert into car (make, model, price) values ('Kia', 'Carens', 8367.35);
insert into car (make, model, price) values ('Toyota', 'Prius c', 3637.74);
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', 17129.04);
insert into car (make, model, price) values ('Dodge', 'Stratus', 5006.92);
insert into car (make, model, price) values ('Infiniti', 'Q', 13357.72);
insert into car (make, model, price) values ('Toyota', 'Celica', 5286.13);
insert into car (make, model, price) values ('Dodge', 'Dakota Club', 16739.83);
insert into car (make, model, price) values ('Ford', 'Excursion', 10217.08);
insert into car (make, model, price) values ('Ford', 'Escape', 3341.56);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 17983.18);
insert into car (make, model, price) values ('Audi', 'V8', 7949.97);
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', 16333.44);
insert into car (make, model, price) values ('Subaru', 'XT', 16576.42);
insert into car (make, model, price) values ('Toyota', 'Highlander', 17905.85);
insert into car (make, model, price) values ('Jeep', 'Cherokee', 4841.58);
insert into car (make, model, price) values ('BMW', 'Z4 M Roadster', 17574.96);
insert into car (make, model, price) values ('Toyota', 'Celica', 4147.88);
insert into car (make, model, price) values ('Mazda', 'MX-5', 10189.88);
insert into car (make, model, price) values ('Mazda', 'GLC', 19121.38);
insert into car (make, model, price) values ('Audi', 'A6', 18450.59);
insert into car (make, model, price) values ('Mercury', 'Sable', 19567.88);
insert into car (make, model, price) values ('Mazda', 'RX-7', 11346.26);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 8482.1);
insert into car (make, model, price) values ('Toyota', 'Sienna', 4703.89);
insert into car (make, model, price) values ('Mazda', 'CX-9', 16081.17);
insert into car (make, model, price) values ('Dodge', 'Avenger', 3343.32);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 9426.28);
insert into car (make, model, price) values ('Isuzu', 'Rodeo', 19074.26);
insert into car (make, model, price) values ('BMW', 'M6', 16178.92);
insert into car (make, model, price) values ('Lexus', 'LS', 17411.6);
insert into car (make, model, price) values ('Honda', 'Accord Crosstour', 19212.83);
insert into car (make, model, price) values ('Chevrolet', 'Caprice', 17252.63);
insert into car (make, model, price) values ('Porsche', '911', 14649.86);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 7198.88);
insert into car (make, model, price) values ('Chevrolet', 'Beretta', 5816.6);
insert into car (make, model, price) values ('Aston Martin', 'Vanquish S', 12558.96);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 19393.14);
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage S', 4883.96);
insert into car (make, model, price) values ('Honda', 'Accord', 10304.15);
insert into car (make, model, price) values ('Jaguar', 'XJ', 8399.88);
insert into car (make, model, price) values ('BMW', 'Alpina B7', 15094.12);
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', 3774.57);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 5168.31);
insert into car (make, model, price) values ('BMW', '760', 14309.39);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 11098.76);
insert into car (make, model, price) values ('Dodge', 'Durango', 9999.04);
insert into car (make, model, price) values ('Lexus', 'GX', 9840.46);
insert into car (make, model, price) values ('Cadillac', 'XLR', 19945.05);
insert into car (make, model, price) values ('BMW', '3 Series', 19358.34);
insert into car (make, model, price) values ('Buick', 'Skylark', 10899.72);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 5105.96);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', 10042.44);
insert into car (make, model, price) values ('Scion', 'xB', 11900.18);
insert into car (make, model, price) values ('GMC', 'Yukon', 13259.29);
insert into car (make, model, price) values ('Toyota', 'MR2', 6062.02);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 2576.08);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 17820.45);
insert into car (make, model, price) values ('Volkswagen', 'Touareg', 4874.29);
insert into car (make, model, price) values ('Audi', '200', 8593.13);
insert into car (make, model, price) values ('Cadillac', 'SRX', 13317.66);
insert into car (make, model, price) values ('Acura', 'MDX', 15243.25);
insert into car (make, model, price) values ('GMC', 'Suburban 2500', 12261.03);
insert into car (make, model, price) values ('Audi', 'R8', 6615.36);
insert into car (make, model, price) values ('Land Rover', 'Defender', 9721.11);
insert into car (make, model, price) values ('Lamborghini', 'Diablo', 2038.85);
insert into car (make, model, price) values ('Porsche', 'Cayenne', 15154.54);
insert into car (make, model, price) values ('Bentley', 'Continental Flying Spur', 5246.81);
insert into car (make, model, price) values ('Saturn', 'S-Series', 3921.51);
insert into car (make, model, price) values ('Chrysler', '300', 10772.93);
insert into car (make, model, price) values ('Pontiac', 'LeMans', 4447.87);
insert into car (make, model, price) values ('Toyota', 'Solara', 4946.04);
insert into car (make, model, price) values ('Acura', 'MDX', 19281.52);
insert into car (make, model, price) values ('Buick', 'Park Avenue', 16375.26);
insert into car (make, model, price) values ('Suzuki', 'Vitara', 10799.07);
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', 2496.34);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 12286.82);
insert into car (make, model, price) values ('Subaru', 'Justy', 10586.79);
insert into car (make, model, price) values ('Ford', 'Taurus X', 12268.6);
insert into car (make, model, price) values ('Buick', 'Riviera', 14840.33);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 14186.41);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 8282.12);
insert into car (make, model, price) values ('Lexus', 'IS', 6851.06);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', 5689.22);
insert into car (make, model, price) values ('Subaru', 'Legacy', 8950.36);
insert into car (make, model, price) values ('Chevrolet', '1500', 11112.5);
insert into car (make, model, price) values ('Mazda', 'B-Series', 15890.36);
insert into car (make, model, price) values ('Audi', 'Q7', 3544.26);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 11555.95);
insert into car (make, model, price) values ('Jaguar', 'XK Series', 11438.49);
insert into car (make, model, price) values ('Audi', 'Allroad', 4110.01);
insert into car (make, model, price) values ('Mazda', 'MX-5', 4897.15);
insert into car (make, model, price) values ('Buick', 'Lucerne', 15161.33);
insert into car (make, model, price) values ('Lotus', 'Elise', 13115.77);
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', 17373.69);
insert into car (make, model, price) values ('Dodge', 'Nitro', 17152.61);
insert into car (make, model, price) values ('Cadillac', 'DeVille', 18976.15);
insert into car (make, model, price) values ('Ford', 'E250', 11876.38);
insert into car (make, model, price) values ('Chrysler', 'Concorde', 10535.26);
insert into car (make, model, price) values ('Mazda', 'Mazda6', 6220.0);
insert into car (make, model, price) values ('Honda', 'Element', 15932.47);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 2315.21);
insert into car (make, model, price) values ('Mercury', 'Monterey', 17682.93);
insert into car (make, model, price) values ('Ford', 'Econoline E350', 8582.98);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', 19456.0);
insert into car (make, model, price) values ('Ford', 'F250', 8703.1);
insert into car (make, model, price) values ('Pontiac', 'Montana', 19853.86);
insert into car (make, model, price) values ('Honda', 'CR-V', 7082.34);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 12920.07);
insert into car (make, model, price) values ('GMC', 'Yukon', 8551.68);
insert into car (make, model, price) values ('Chevrolet', 'Prizm', 11937.6);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 16285.65);
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', 19292.58);
insert into car (make, model, price) values ('Buick', 'LeSabre', 2736.44);
insert into car (make, model, price) values ('Toyota', 'Prius c', 2947.86);
insert into car (make, model, price) values ('Buick', 'Riviera', 13472.66);
insert into car (make, model, price) values ('Chevrolet', 'Caprice', 14206.72);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 3801.79);
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', 18543.82);
insert into car (make, model, price) values ('Nissan', 'Stanza', 7255.13);
insert into car (make, model, price) values ('Mercury', 'Capri', 6031.74);
insert into car (make, model, price) values ('Audi', 'S6', 11101.23);
insert into car (make, model, price) values ('BMW', 'M3', 15637.64);
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', 2763.28);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 13169.95);
insert into car (make, model, price) values ('Lincoln', 'Mark LT', 11143.21);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 9096.1);
insert into car (make, model, price) values ('Ford', 'Ranger', 8844.81);
insert into car (make, model, price) values ('Hyundai', 'Veracruz', 9902.51);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 5508.04);
insert into car (make, model, price) values ('Jaguar', 'XK', 16780.6);
insert into car (make, model, price) values ('Saturn', 'VUE', 8657.45);
insert into car (make, model, price) values ('Mazda', 'Tribute', 14203.81);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 11392.09);
insert into car (make, model, price) values ('Ford', 'LTD Crown Victoria', 12637.97);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 2638.84);
insert into car (make, model, price) values ('Cadillac', 'SRX', 7210.91);
insert into car (make, model, price) values ('Toyota', '4Runner', 6771.31);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 15319.92);
insert into car (make, model, price) values ('Cadillac', 'Seville', 16566.55);
insert into car (make, model, price) values ('Saturn', 'VUE', 12318.78);
insert into car (make, model, price) values ('Kia', 'Sorento', 8954.21);
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', 2348.39);
insert into car (make, model, price) values ('GMC', 'Suburban 1500', 12427.7);
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B350', 12979.93);
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', 16548.26);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 10829.61);
insert into car (make, model, price) values ('Audi', 'A5', 19922.27);
insert into car (make, model, price) values ('Volvo', 'V70', 17450.92);
insert into car (make, model, price) values ('Lotus', 'Esprit', 12850.93);
insert into car (make, model, price) values ('Chevrolet', 'Cobalt', 18844.03);
insert into car (make, model, price) values ('Audi', 'A4', 4372.39);
insert into car (make, model, price) values ('Ford', 'Explorer Sport', 7761.35);
insert into car (make, model, price) values ('Ford', 'LTD', 13635.65);
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G30', 13702.32);
insert into car (make, model, price) values ('Maserati', '430', 19479.69);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 13903.85);
insert into car (make, model, price) values ('Ferrari', 'California', 11397.57);
insert into car (make, model, price) values ('Oldsmobile', 'Toronado', 16251.63);
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', 16836.05);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 10474.71);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 18048.68);
insert into car (make, model, price) values ('Lexus', 'RX', 19249.97);
insert into car (make, model, price) values ('Acura', 'Vigor', 8286.14);
insert into car (make, model, price) values ('Buick', 'Century', 11992.44);
insert into car (make, model, price) values ('Mazda', 'Tribute', 5816.46);
insert into car (make, model, price) values ('Ford', 'Econoline E250', 4239.12);
insert into car (make, model, price) values ('Mercedes-Benz', 'G55 AMG', 8387.85);
insert into car (make, model, price) values ('Aston Martin', 'Vantage', 4467.77);
insert into car (make, model, price) values ('Lotus', 'Esprit', 4610.68);
insert into car (make, model, price) values ('Mercury', 'Cougar', 6010.07);
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', 12995.47);
insert into car (make, model, price) values ('Chevrolet', 'Corvair', 18694.61);
insert into car (make, model, price) values ('Subaru', 'Legacy', 15776.54);
insert into car (make, model, price) values ('Toyota', 'Echo', 10092.97);
insert into car (make, model, price) values ('Toyota', 'Highlander', 8318.71);
insert into car (make, model, price) values ('Mazda', '626', 17871.56);
insert into car (make, model, price) values ('Subaru', 'Leone', 15458.57);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 11992.44);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 17026.17);
insert into car (make, model, price) values ('Nissan', 'Maxima', 13518.35);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 8838.55);
insert into car (make, model, price) values ('Cadillac', 'STS', 15735.21);
insert into car (make, model, price) values ('Ford', 'Fusion', 17147.93);
insert into car (make, model, price) values ('Ford', 'Ranger', 12199.52);
insert into car (make, model, price) values ('Ford', 'F-350 Super Duty', 18385.57);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 4697.27);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 10687.87);
insert into car (make, model, price) values ('Ford', 'Tempo', 13817.42);
insert into car (make, model, price) values ('Lexus', 'RX', 17283.87);
insert into car (make, model, price) values ('Isuzu', 'Stylus', 8092.83);
insert into car (make, model, price) values ('Audi', '100', 15935.48);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 3974.15);
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', 14352.39);
insert into car (make, model, price) values ('Porsche', '914', 13255.44);
insert into car (make, model, price) values ('Eagle', 'Talon', 19507.99);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 8263.3);
insert into car (make, model, price) values ('Nissan', 'NX', 3774.53);
insert into car (make, model, price) values ('Chevrolet', '3500', 18231.06);
insert into car (make, model, price) values ('Pontiac', 'Torrent', 8599.43);
insert into car (make, model, price) values ('GMC', 'Envoy XL', 13486.81);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 15933.42);
insert into car (make, model, price) values ('Mazda', 'Protege', 17739.45);
insert into car (make, model, price) values ('Dodge', 'D350 Club', 2820.71);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 6262.7);
insert into car (make, model, price) values ('Buick', 'Rendezvous', 18939.72);
insert into car (make, model, price) values ('Dodge', 'Ram 1500', 19144.93);
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', 12560.43);
insert into car (make, model, price) values ('Chrysler', '300', 13425.88);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 4312.59);
insert into car (make, model, price) values ('Cadillac', 'Catera', 18112.38);
insert into car (make, model, price) values ('Plymouth', 'Breeze', 13285.1);
insert into car (make, model, price) values ('Audi', 'A3', 13922.71);
insert into car (make, model, price) values ('Buick', 'Regal', 4099.2);
insert into car (make, model, price) values ('Mazda', 'MX-5', 17202.69);
insert into car (make, model, price) values ('Lincoln', 'Navigator', 19842.42);
insert into car (make, model, price) values ('Nissan', 'Titan', 16407.82);
insert into car (make, model, price) values ('MINI', 'Clubman', 2527.37);
insert into car (make, model, price) values ('Nissan', 'Frontier', 9628.13);
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', 14941.81);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 17747.94);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 2981.63);
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', 9468.17);
insert into car (make, model, price) values ('Mazda', '626', 19817.1);
insert into car (make, model, price) values ('Toyota', 'Yaris', 11706.13);
insert into car (make, model, price) values ('Audi', 'TT', 6634.18);
insert into car (make, model, price) values ('GMC', 'Sierra 1500', 9541.73);
insert into car (make, model, price) values ('Buick', 'LeSabre', 9305.03);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 2840.44);
insert into car (make, model, price) values ('Mazda', 'CX-9', 17421.44);
insert into car (make, model, price) values ('Plymouth', 'Prowler', 4980.03);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 15193.52);
insert into car (make, model, price) values ('Mitsubishi', 'Starion', 19116.32);
insert into car (make, model, price) values ('Dodge', 'Charger', 7214.41);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 5215.07);
insert into car (make, model, price) values ('Dodge', 'Caravan', 16583.48);
insert into car (make, model, price) values ('Volvo', 'S40', 17464.45);
insert into car (make, model, price) values ('Mazda', 'RX-8', 4766.36);
insert into car (make, model, price) values ('Pontiac', 'G5', 3351.5);
insert into car (make, model, price) values ('Toyota', 'Previa', 7885.99);
insert into car (make, model, price) values ('Aston Martin', 'V12 Vantage', 5929.16);
insert into car (make, model, price) values ('Cadillac', 'SRX', 3438.91);
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', 6564.53);
insert into car (make, model, price) values ('Suzuki', 'SJ', 16197.42);
insert into car (make, model, price) values ('Mazda', 'MPV', 19724.71);
insert into car (make, model, price) values ('Porsche', 'Boxster', 6791.76);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 10310.26);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 2830.69);
insert into car (make, model, price) values ('Honda', 'Civic', 9756.06);
insert into car (make, model, price) values ('Scion', 'tC', 11063.75);
insert into car (make, model, price) values ('Saturn', 'VUE', 2912.75);
insert into car (make, model, price) values ('Chrysler', '300M', 15018.7);
insert into car (make, model, price) values ('Hyundai', 'Azera', 10732.44);
insert into car (make, model, price) values ('Ford', 'Mustang', 15384.71);
insert into car (make, model, price) values ('Mazda', 'MX-5', 16957.37);
insert into car (make, model, price) values ('GMC', 'Sierra 1500', 9735.39);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 15512.04);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 17549.76);
insert into car (make, model, price) values ('Audi', 'Cabriolet', 4986.84);
insert into car (make, model, price) values ('Ford', 'Transit Connect', 12652.81);
insert into car (make, model, price) values ('Honda', 'Pilot', 6501.92);
insert into car (make, model, price) values ('Plymouth', 'Colt', 17063.02);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 17115.77);
insert into car (make, model, price) values ('BMW', 'M3', 2331.52);
insert into car (make, model, price) values ('Volvo', 'C70', 4696.21);
insert into car (make, model, price) values ('Chevrolet', 'G-Series 2500', 8903.86);
insert into car (make, model, price) values ('Spyker', 'C8 Double 12 S', 4344.03);
insert into car (make, model, price) values ('Saturn', 'Outlook', 11317.55);
insert into car (make, model, price) values ('Chrysler', '300', 15667.17);
insert into car (make, model, price) values ('Nissan', '370Z', 11090.6);
insert into car (make, model, price) values ('BMW', 'Z3', 9744.59);
insert into car (make, model, price) values ('Ford', 'Explorer', 3558.63);
insert into car (make, model, price) values ('Lincoln', 'LS', 3303.74);
insert into car (make, model, price) values ('Hyundai', 'Tiburon', 6722.78);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 3327.04);
insert into car (make, model, price) values ('Volvo', 'S90', 6266.0);
insert into car (make, model, price) values ('Ford', 'Excursion', 10855.21);
insert into car (make, model, price) values ('Mitsubishi', 'Precis', 18837.48);
insert into car (make, model, price) values ('Volkswagen', 'Rabbit', 9496.68);
insert into car (make, model, price) values ('Mitsubishi', 'Precis', 15146.2);
insert into car (make, model, price) values ('Mercury', 'Montego', 4706.54);
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', 19579.57);
insert into car (make, model, price) values ('Lexus', 'LX', 4865.9);
insert into car (make, model, price) values ('Lotus', 'Esprit', 2156.95);
insert into car (make, model, price) values ('Audi', 'TT', 19071.95);
insert into car (make, model, price) values ('Volvo', 'S40', 17348.45);
insert into car (make, model, price) values ('Lexus', 'SC', 15406.24);
insert into car (make, model, price) values ('Mitsubishi', 'Truck', 19410.63);
insert into car (make, model, price) values ('BMW', 'M5', 12659.88);
insert into car (make, model, price) values ('Pontiac', 'Sunfire', 4676.5);
insert into car (make, model, price) values ('Oldsmobile', '88', 10396.26);
insert into car (make, model, price) values ('Honda', 'Civic', 2497.95);
insert into car (make, model, price) values ('Saab', '9-3', 19813.07);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 7315.79);
insert into car (make, model, price) values ('Audi', 'A4', 2117.58);
insert into car (make, model, price) values ('Volvo', 'XC90', 11434.77);
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', 2249.09);
insert into car (make, model, price) values ('GMC', 'Safari', 16103.69);
insert into car (make, model, price) values ('Pontiac', 'Sunbird', 8389.85);
insert into car (make, model, price) values ('Mitsubishi', 'Montero', 11238.92);
insert into car (make, model, price) values ('Toyota', 'Celica', 3724.69);
insert into car (make, model, price) values ('Subaru', 'Legacy', 11936.82);
insert into car (make, model, price) values ('Toyota', 'Corolla', 17233.72);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 13596.04);
insert into car (make, model, price) values ('Pontiac', 'Montana', 17631.14);
insert into car (make, model, price) values ('Audi', 'S5', 3463.29);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 2821.07);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 2098.88);
insert into car (make, model, price) values ('Toyota', 'Prius', 15533.42);
insert into car (make, model, price) values ('Nissan', 'Sentra', 12077.67);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 5919.84);
insert into car (make, model, price) values ('Chevrolet', 'Corvair 500', 14324.9);
insert into car (make, model, price) values ('Volkswagen', 'CC', 14674.38);
insert into car (make, model, price) values ('Buick', 'Skylark', 7579.33);
insert into car (make, model, price) values ('Kia', 'Spectra', 18695.96);
insert into car (make, model, price) values ('Subaru', 'Impreza', 16348.95);
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', 6857.57);
insert into car (make, model, price) values ('Land Rover', 'Defender', 12599.72);
insert into car (make, model, price) values ('Mercury', 'Villager', 18859.15);
insert into car (make, model, price) values ('Nissan', 'Altima', 2124.7);
insert into car (make, model, price) values ('Toyota', 'Sequoia', 5928.89);
insert into car (make, model, price) values ('Mazda', 'RX-7', 8614.45);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 6105.77);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 7994.39);
insert into car (make, model, price) values ('Kia', 'Spectra', 19670.74);
insert into car (make, model, price) values ('Acura', 'SLX', 9214.81);
insert into car (make, model, price) values ('Ford', 'E350', 14108.37);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 14676.97);
insert into car (make, model, price) values ('Porsche', 'Cayenne', 10969.57);
insert into car (make, model, price) values ('Saab', '9000', 11399.75);
insert into car (make, model, price) values ('Porsche', '911', 17379.87);
insert into car (make, model, price) values ('Mazda', 'B-Series', 11622.4);
insert into car (make, model, price) values ('Volvo', '960', 3177.89);
insert into car (make, model, price) values ('Ford', 'Econoline E250', 8070.81);
insert into car (make, model, price) values ('Isuzu', 'i-370', 5976.58);
insert into car (make, model, price) values ('Lexus', 'GS', 3284.56);
insert into car (make, model, price) values ('MINI', 'Cooper Clubman', 5734.76);
insert into car (make, model, price) values ('Mercedes-Benz', '300D', 2874.2);
insert into car (make, model, price) values ('Buick', 'Century', 15124.12);
insert into car (make, model, price) values ('Mercury', 'Sable', 7171.24);
insert into car (make, model, price) values ('Ford', 'Expedition', 14409.33);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 19574.03);
insert into car (make, model, price) values ('Volvo', '960', 11711.74);
insert into car (make, model, price) values ('Audi', 'Q5', 12083.32);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 18978.95);
insert into car (make, model, price) values ('Ferrari', '599 GTB Fiorano', 12852.58);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 18600.54);
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass', 17574.94);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 17772.06);
insert into car (make, model, price) values ('Volvo', 'V40', 14824.16);
insert into car (make, model, price) values ('Mazda', 'Protege', 12758.03);
insert into car (make, model, price) values ('Cadillac', 'Escalade', 14363.7);
insert into car (make, model, price) values ('Mercedes-Benz', 'W126', 9152.47);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 6621.85);
insert into car (make, model, price) values ('Ford', 'F-Series', 6506.05);
insert into car (make, model, price) values ('Ford', 'Focus', 11184.92);
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', 17763.36);
insert into car (make, model, price) values ('Hummer', 'H3', 16237.75);
insert into car (make, model, price) values ('Lincoln', 'Continental', 6221.58);
insert into car (make, model, price) values ('GMC', 'Safari', 19021.14);
insert into car (make, model, price) values ('Ferrari', 'California', 4712.09);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 11920.46);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 16020.16);
insert into car (make, model, price) values ('Bentley', 'Continental GT', 5822.37);
insert into car (make, model, price) values ('Mazda', 'RX-8', 7796.71);
insert into car (make, model, price) values ('Buick', 'Park Avenue', 16512.5);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 16614.24);
insert into car (make, model, price) values ('BMW', '5 Series', 16960.23);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 10719.09);
insert into car (make, model, price) values ('Lexus', 'RX', 13073.7);
insert into car (make, model, price) values ('Volvo', 'S70', 2709.27);
insert into car (make, model, price) values ('Jaguar', 'XK', 8512.59);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', 19191.0);
insert into car (make, model, price) values ('Dodge', 'D250 Club', 10288.05);
insert into car (make, model, price) values ('Mazda', 'MX-5', 9182.99);
insert into car (make, model, price) values ('GMC', 'Rally Wagon 2500', 6288.09);
insert into car (make, model, price) values ('Chevrolet', '2500', 7433.16);
insert into car (make, model, price) values ('Audi', 'A4', 10196.11);
insert into car (make, model, price) values ('Ford', 'Ranger', 9273.43);
insert into car (make, model, price) values ('Honda', 'Passport', 3226.61);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 7327.67);
insert into car (make, model, price) values ('BMW', 'X5', 15299.88);
insert into car (make, model, price) values ('Cadillac', 'DeVille', 10165.4);
insert into car (make, model, price) values ('Holden', 'VS Commodore', 17089.59);
insert into car (make, model, price) values ('Saturn', 'VUE', 18729.0);
insert into car (make, model, price) values ('Ford', 'Ranger', 2381.91);
insert into car (make, model, price) values ('Chrysler', '300', 18606.07);
insert into car (make, model, price) values ('Ford', 'Taurus', 12726.62);
insert into car (make, model, price) values ('Dodge', 'Ram 2500', 16203.37);
insert into car (make, model, price) values ('Saab', '900', 17443.12);
insert into car (make, model, price) values ('BMW', '7 Series', 4060.07);
insert into car (make, model, price) values ('Hummer', 'H1', 15530.18);
insert into car (make, model, price) values ('Volkswagen', 'Touareg', 7813.77);
insert into car (make, model, price) values ('Scion', 'xD', 8754.6);
insert into car (make, model, price) values ('Jeep', 'Liberty', 5777.33);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 3048.8);
insert into car (make, model, price) values ('MINI', 'Cooper', 17745.6);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 3914.0);
insert into car (make, model, price) values ('Maserati', 'Gran Sport', 16682.92);
insert into car (make, model, price) values ('Hyundai', 'Tiburon', 14675.64);
insert into car (make, model, price) values ('GMC', 'Suburban 2500', 5499.69);
insert into car (make, model, price) values ('Buick', 'LeSabre', 3919.63);
insert into car (make, model, price) values ('Honda', 'Civic', 2355.08);
insert into car (make, model, price) values ('Audi', 'Coupe GT', 18851.68);
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', 11915.01);
insert into car (make, model, price) values ('Lotus', 'Esprit', 15664.23);
insert into car (make, model, price) values ('Ford', 'Ranger', 10971.38);
insert into car (make, model, price) values ('Nissan', 'Quest', 14263.06);
insert into car (make, model, price) values ('Volvo', 'S40', 12406.06);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 17741.65);
insert into car (make, model, price) values ('Pontiac', 'Parisienne', 6232.83);
insert into car (make, model, price) values ('Buick', 'LeSabre', 17214.03);
insert into car (make, model, price) values ('BMW', '750', 11485.14);
insert into car (make, model, price) values ('Hummer', 'H1', 5725.57);
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', 14170.71);
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', 10129.13);
insert into car (make, model, price) values ('Volvo', 'XC70', 18982.75);
insert into car (make, model, price) values ('Subaru', 'Impreza', 16672.08);
insert into car (make, model, price) values ('Mazda', 'B-Series', 16177.99);
insert into car (make, model, price) values ('Ford', 'E-Series', 17729.81);
insert into car (make, model, price) values ('Mazda', 'Protege5', 7596.65);
insert into car (make, model, price) values ('Pontiac', 'GTO', 10995.09);
insert into car (make, model, price) values ('Chevrolet', 'Express', 11253.91);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 19763.21);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 19843.72);
insert into car (make, model, price) values ('Mitsubishi', '3000GT', 17766.68);
insert into car (make, model, price) values ('Toyota', 'Yaris', 7540.54);
insert into car (make, model, price) values ('Audi', 'A8', 13336.09);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 2246.31);
insert into car (make, model, price) values ('Honda', 'Prelude', 11906.82);
insert into car (make, model, price) values ('Hyundai', 'Veracruz', 11369.57);
insert into car (make, model, price) values ('Toyota', 'Avalon', 12055.63);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', 19892.9);
insert into car (make, model, price) values ('BMW', '3 Series', 9726.62);
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', 14774.49);
insert into car (make, model, price) values ('Ford', 'Focus', 5480.88);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 16197.22);
insert into car (make, model, price) values ('Jaguar', 'XF', 6971.2);
insert into car (make, model, price) values ('Lincoln', 'MKS', 2408.34);
insert into car (make, model, price) values ('Ford', 'Econoline E250', 17631.9);
insert into car (make, model, price) values ('Toyota', 'Corolla', 14196.5);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 17222.98);
insert into car (make, model, price) values ('Fairthorpe', 'Rockette', 16440.6);
insert into car (make, model, price) values ('Lotus', 'Esprit Turbo', 9384.17);
insert into car (make, model, price) values ('Nissan', 'Murano', 18754.65);
insert into car (make, model, price) values ('Ford', 'Mustang', 13342.93);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 9077.33);
insert into car (make, model, price) values ('Audi', 'RS 6', 12122.44);
insert into car (make, model, price) values ('Mercury', 'Sable', 16109.17);
insert into car (make, model, price) values ('Ford', 'Mustang', 13181.34);
insert into car (make, model, price) values ('Nissan', '240SX', 11908.74);
insert into car (make, model, price) values ('Mazda', 'Mazda6', 12946.55);
insert into car (make, model, price) values ('Nissan', 'Armada', 19680.49);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 9576.22);
insert into car (make, model, price) values ('BMW', '5 Series', 6704.54);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 7349.95);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 2508.48);
insert into car (make, model, price) values ('Chevrolet', '3500', 2830.0);
insert into car (make, model, price) values ('Kia', 'Sportage', 2861.92);
insert into car (make, model, price) values ('Saab', '9-3', 4599.93);
insert into car (make, model, price) values ('Toyota', 'Tercel', 17565.16);
insert into car (make, model, price) values ('Saab', '9-7X', 8406.82);
insert into car (make, model, price) values ('Mitsubishi', 'Truck', 18341.13);
insert into car (make, model, price) values ('Dodge', 'Ram 2500 Club', 10041.43);
insert into car (make, model, price) values ('BMW', 'Z3', 8532.75);
insert into car (make, model, price) values ('Audi', 'A6', 12875.76);
insert into car (make, model, price) values ('Audi', 'A8', 14181.86);
insert into car (make, model, price) values ('Chevrolet', 'Silverado Hybrid', 18008.97);
insert into car (make, model, price) values ('Ford', 'Falcon', 4918.89);
insert into car (make, model, price) values ('Chrysler', '200', 14336.01);
insert into car (make, model, price) values ('Nissan', 'Xterra', 4644.38);
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', 2221.56);
insert into car (make, model, price) values ('Saturn', 'S-Series', 10869.35);
insert into car (make, model, price) values ('Mazda', 'Familia', 17507.09);
insert into car (make, model, price) values ('Infiniti', 'G', 11169.35);
insert into car (make, model, price) values ('Mitsubishi', 'Truck', 7537.87);
insert into car (make, model, price) values ('Ford', 'Bronco', 15028.47);
insert into car (make, model, price) values ('Chevrolet', 'APV', 16833.93);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 13265.66);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 17814.06);
insert into car (make, model, price) values ('Subaru', 'Legacy', 15719.96);
insert into car (make, model, price) values ('Isuzu', 'Trooper', 16388.79);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 7815.9);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 13412.1);
insert into car (make, model, price) values ('Pontiac', '6000', 16570.49);
insert into car (make, model, price) values ('Maserati', 'Biturbo', 9498.44);
insert into car (make, model, price) values ('Scion', 'tC', 12207.76);
insert into car (make, model, price) values ('Suzuki', 'Esteem', 5318.76);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 15000.22);
insert into car (make, model, price) values ('Nissan', 'Sentra', 13550.91);
insert into car (make, model, price) values ('Porsche', 'Boxster', 19744.87);
insert into car (make, model, price) values ('Hummer', 'H2', 8880.69);
insert into car (make, model, price) values ('GMC', 'Sierra Denali', 13391.99);
insert into car (make, model, price) values ('Mercedes-Benz', 'W126', 8319.34);
insert into car (make, model, price) values ('Mitsubishi', 'Starion', 19662.15);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 4132.81);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 15211.04);
insert into car (make, model, price) values ('Lincoln', 'Mark VII', 2950.74);
insert into car (make, model, price) values ('Kia', 'Sorento', 8819.76);
insert into car (make, model, price) values ('Audi', 'A3', 2140.21);
insert into car (make, model, price) values ('Geo', 'Metro', 17152.78);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 9134.07);
insert into car (make, model, price) values ('Austin', 'Mini', 8871.66);
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', 9034.91);
insert into car (make, model, price) values ('Cadillac', 'XLR-V', 10724.83);
insert into car (make, model, price) values ('Volkswagen', 'Passat', 19890.12);
insert into car (make, model, price) values ('Hyundai', 'Accent', 4361.09);
insert into car (make, model, price) values ('Honda', 'Ridgeline', 19178.61);
insert into car (make, model, price) values ('Lexus', 'GX', 18396.41);
insert into car (make, model, price) values ('Subaru', 'Outback', 8510.08);
insert into car (make, model, price) values ('Isuzu', 'Axiom', 15779.26);
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', 5064.48);
insert into car (make, model, price) values ('Chrysler', 'Sebring', 7423.24);
insert into car (make, model, price) values ('Toyota', 'Prius', 14629.48);
insert into car (make, model, price) values ('Nissan', 'Maxima', 6573.94);
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', 6980.66);
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', 10418.48);
insert into car (make, model, price) values ('Honda', 'Accord', 13972.72);
insert into car (make, model, price) values ('Ford', 'Mustang', 5621.53);
insert into car (make, model, price) values ('Nissan', 'Titan', 16016.77);
insert into car (make, model, price) values ('Ford', 'Windstar', 10006.44);
insert into car (make, model, price) values ('Honda', 'Accord', 18460.34);
insert into car (make, model, price) values ('Isuzu', 'Hombre Space', 17743.96);
insert into car (make, model, price) values ('Chevrolet', 'Caprice Classic', 18822.37);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 2730.04);
insert into car (make, model, price) values ('Nissan', '350Z', 5747.38);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 12961.12);
insert into car (make, model, price) values ('Lincoln', 'LS', 7882.15);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', 18831.74);
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', 10025.98);
insert into car (make, model, price) values ('Ford', 'GT500', 4418.1);
insert into car (make, model, price) values ('Toyota', 'RAV4', 5742.49);
insert into car (make, model, price) values ('Nissan', 'Quest', 6612.4);
insert into car (make, model, price) values ('Ford', 'E350', 15632.69);
insert into car (make, model, price) values ('Dodge', 'Stratus', 4666.69);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 17848.19);
insert into car (make, model, price) values ('Saab', '9-3', 4648.81);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 14911.29);
insert into car (make, model, price) values ('Toyota', 'Tundra', 14711.84);
insert into car (make, model, price) values ('Isuzu', 'Ascender', 18263.25);
insert into car (make, model, price) values ('GMC', 'Sierra 3500', 4749.38);
insert into car (make, model, price) values ('Aston Martin', 'DB9', 4677.78);
insert into car (make, model, price) values ('BMW', '525', 15654.43);
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', 11111.18);
insert into car (make, model, price) values ('Nissan', 'Sentra', 13076.19);
insert into car (make, model, price) values ('Ford', 'Escape', 13851.54);
insert into car (make, model, price) values ('BMW', 'X5', 9259.91);
insert into car (make, model, price) values ('Audi', 'TT', 9720.7);
insert into car (make, model, price) values ('Infiniti', 'J', 11751.47);
insert into car (make, model, price) values ('Lexus', 'GX', 2981.83);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 6883.09);
insert into car (make, model, price) values ('Chevrolet', 'Tracker', 18261.34);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 14018.59);
insert into car (make, model, price) values ('Suzuki', 'SX4', 6029.12);
insert into car (make, model, price) values ('Isuzu', 'Space', 11115.65);
insert into car (make, model, price) values ('Nissan', 'Versa', 2981.78);
insert into car (make, model, price) values ('GMC', 'Savana 2500', 7903.27);
insert into car (make, model, price) values ('Porsche', 'Boxster', 9183.63);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 4211.83);
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', 10013.31);
insert into car (make, model, price) values ('Mazda', 'RX-7', 10252.97);
insert into car (make, model, price) values ('Audi', 'Cabriolet', 6417.1);
insert into car (make, model, price) values ('Lotus', 'Esprit', 15560.29);
insert into car (make, model, price) values ('Ford', 'F150', 19002.25);
insert into car (make, model, price) values ('Ford', 'Explorer', 2682.21);
insert into car (make, model, price) values ('Chrysler', 'Imperial', 17288.67);
insert into car (make, model, price) values ('Toyota', 'MR2', 16445.54);
insert into car (make, model, price) values ('Honda', 'del Sol', 12706.12);
insert into car (make, model, price) values ('Mercedes-Benz', 'W126', 19554.35);
insert into car (make, model, price) values ('Mitsubishi', 'Montero', 5304.85);
insert into car (make, model, price) values ('Mercury', 'Monterey', 14234.96);
insert into car (make, model, price) values ('Jeep', 'Patriot', 11121.15);
insert into car (make, model, price) values ('Ford', 'F150', 3534.81);
insert into car (make, model, price) values ('Infiniti', 'Q', 18870.32);
insert into car (make, model, price) values ('Ford', 'Fusion', 11054.92);
insert into car (make, model, price) values ('Chrysler', 'Pacifica', 14002.53);
insert into car (make, model, price) values ('BMW', 'X5', 3242.34);
insert into car (make, model, price) values ('Dodge', 'Caravan', 3407.56);
insert into car (make, model, price) values ('MINI', 'Clubman', 16543.96);
insert into car (make, model, price) values ('Land Rover', 'Discovery Series II', 4431.25);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 16205.68);
insert into car (make, model, price) values ('Bentley', 'Azure', 18402.68);
insert into car (make, model, price) values ('BMW', '5 Series', 16531.2);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 18110.21);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 14472.8);
insert into car (make, model, price) values ('Ford', 'Festiva', 16373.36);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', 19392.28);
insert into car (make, model, price) values ('Mazda', 'RX-7', 12365.7);
insert into car (make, model, price) values ('GMC', 'Sonoma', 9956.96);
insert into car (make, model, price) values ('Kia', 'Sedona', 9813.72);
insert into car (make, model, price) values ('Mercedes-Benz', 'GL-Class', 7730.02);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 14418.79);
insert into car (make, model, price) values ('Lexus', 'IS-F', 18682.66);
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', 14905.91);
insert into car (make, model, price) values ('Chevrolet', 'Cruze', 3527.31);
insert into car (make, model, price) values ('Isuzu', 'Amigo', 2367.92);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 5112.55);
insert into car (make, model, price) values ('Toyota', 'Prius', 4192.86);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 12165.77);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 12433.35);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 10403.41);
insert into car (make, model, price) values ('Land Rover', 'Defender 90', 13495.12);
insert into car (make, model, price) values ('Honda', 'Civic', 13898.18);
insert into car (make, model, price) values ('Toyota', 'Paseo', 5598.83);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 18354.64);
insert into car (make, model, price) values ('Honda', 'Civic', 3917.11);
insert into car (make, model, price) values ('Ford', 'F150', 19646.18);
insert into car (make, model, price) values ('Ford', 'Aerostar', 19632.4);
insert into car (make, model, price) values ('Lincoln', 'Navigator', 12606.31);
insert into car (make, model, price) values ('Jeep', 'Commander', 15028.89);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 13679.69);
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', 3205.95);
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', 6507.64);
insert into car (make, model, price) values ('Hyundai', 'Elantra', 2912.71);
insert into car (make, model, price) values ('Lincoln', 'Zephyr', 11179.43);
insert into car (make, model, price) values ('Geo', 'Tracker', 12487.31);
insert into car (make, model, price) values ('Mazda', 'Protege', 11295.73);
insert into car (make, model, price) values ('Nissan', 'Cube', 2719.0);
insert into car (make, model, price) values ('Mazda', 'B-Series', 9453.39);
insert into car (make, model, price) values ('Nissan', 'Xterra', 2493.45);
insert into car (make, model, price) values ('Suzuki', 'SJ 410', 9139.25);
insert into car (make, model, price) values ('Mercury', 'Cougar', 17391.35);
insert into car (make, model, price) values ('Chevrolet', 'S10 Blazer', 16956.18);
insert into car (make, model, price) values ('Lotus', 'Elise', 17756.8);
insert into car (make, model, price) values ('Audi', 'A7', 4474.23);
insert into car (make, model, price) values ('Mazda', 'MX-3', 10499.5);
insert into car (make, model, price) values ('Land Rover', 'LR2', 13469.48);
insert into car (make, model, price) values ('Ram', '1500', 16716.8);
insert into car (make, model, price) values ('Cadillac', 'DeVille', 7895.82);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 3688.75);
insert into car (make, model, price) values ('BMW', 'X6 M', 19155.58);
insert into car (make, model, price) values ('BMW', '5 Series', 7982.27);
insert into car (make, model, price) values ('Lexus', 'GS', 7414.01);
insert into car (make, model, price) values ('Honda', 'Civic', 15448.84);
insert into car (make, model, price) values ('Audi', 'A6', 9063.25);
insert into car (make, model, price) values ('Dodge', 'Ram 2500', 14587.46);
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', 4667.76);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 12646.54);
insert into car (make, model, price) values ('Acura', 'TL', 5238.1);
insert into car (make, model, price) values ('Aston Martin', 'DBS', 16115.58);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 8657.83);
insert into car (make, model, price) values ('Buick', 'Enclave', 12679.3);
insert into car (make, model, price) values ('Ford', 'F150', 8885.03);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 10844.75);
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', 7780.24);
insert into car (make, model, price) values ('Chevrolet', 'Malibu', 10123.72);
insert into car (make, model, price) values ('Lexus', 'LS Hybrid', 10234.43);
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', 15267.56);
insert into car (make, model, price) values ('Volvo', 'S40', 18585.72);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 6248.79);
insert into car (make, model, price) values ('Buick', 'Century', 12544.95);
insert into car (make, model, price) values ('Mazda', 'Protege', 8934.96);
insert into car (make, model, price) values ('MINI', 'Cooper', 16509.71);
insert into car (make, model, price) values ('Suzuki', 'Swift', 18947.39);
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', 9637.91);
insert into car (make, model, price) values ('Subaru', 'Legacy', 19505.13);
insert into car (make, model, price) values ('Suzuki', 'Daewoo Magnus', 16484.06);
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', 9178.41);
insert into car (make, model, price) values ('Volvo', '850', 9518.09);
insert into car (make, model, price) values ('Pontiac', 'Solstice', 10265.68);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 3442.25);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 6886.48);
insert into car (make, model, price) values ('BMW', 'Z3', 5169.63);
insert into car (make, model, price) values ('Honda', 'Passport', 3858.31);
insert into car (make, model, price) values ('Toyota', '4Runner', 19711.56);
insert into car (make, model, price) values ('Acura', 'TL', 9574.33);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 2462.28);
insert into car (make, model, price) values ('Ford', 'Crown Victoria', 13923.86);
insert into car (make, model, price) values ('Ford', 'LTD Crown Victoria', 6533.41);
insert into car (make, model, price) values ('Chrysler', 'Voyager', 5177.94);
insert into car (make, model, price) values ('Toyota', '4Runner', 4946.35);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 2247.01);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 8017.43);
insert into car (make, model, price) values ('Audi', 'A7', 7686.33);
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', 4305.38);
insert into car (make, model, price) values ('Mercury', 'Sable', 12877.71);
insert into car (make, model, price) values ('Hyundai', 'Tiburon', 10196.26);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 19332.99);
insert into car (make, model, price) values ('Nissan', 'Quest', 11039.94);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 13464.92);
insert into car (make, model, price) values ('Toyota', 'RAV4', 3113.56);
insert into car (make, model, price) values ('Acura', 'NSX', 16291.07);
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', 16911.54);
insert into car (make, model, price) values ('Toyota', 'MR2', 5099.56);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 5493.37);
insert into car (make, model, price) values ('Porsche', 'Boxster', 12196.18);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 5239.94);
insert into car (make, model, price) values ('Audi', 'Quattro', 10522.35);
insert into car (make, model, price) values ('Acura', 'RL', 18357.8);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', 19335.54);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 10757.2);
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage', 6078.83);
insert into car (make, model, price) values ('Ford', 'Probe', 3316.8);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 14568.67);
insert into car (make, model, price) values ('Spyker', 'C8', 19338.54);
insert into car (make, model, price) values ('Audi', '5000S', 6321.61);
insert into car (make, model, price) values ('Mazda', '323', 9618.41);
insert into car (make, model, price) values ('Honda', 'Prelude', 5231.46);
insert into car (make, model, price) values ('Ford', 'E-Series', 15133.23);
insert into car (make, model, price) values ('Saab', '9-3', 12222.79);
insert into car (make, model, price) values ('Suzuki', 'XL7', 6256.89);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 4575.04);
insert into car (make, model, price) values ('Ford', 'Fiesta', 16020.0);
insert into car (make, model, price) values ('Chrysler', 'Voyager', 6752.14);
insert into car (make, model, price) values ('Dodge', 'D150', 14731.64);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 3733.32);
insert into car (make, model, price) values ('Toyota', 'Sienna', 7032.15);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 15777.82);
insert into car (make, model, price) values ('Lexus', 'IS-F', 19026.32);
insert into car (make, model, price) values ('Lexus', 'ES', 2517.31);
insert into car (make, model, price) values ('Acura', 'RL', 7112.73);
insert into car (make, model, price) values ('Mazda', 'MPV', 19982.79);
insert into car (make, model, price) values ('Lexus', 'IS', 9085.59);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 13033.25);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 19865.8);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 11708.3);
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', 7993.28);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 5192.44);
insert into car (make, model, price) values ('Acura', 'CL', 17301.26);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', 6028.41);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 5397.6);
insert into car (make, model, price) values ('Dodge', 'Avenger', 7314.91);
insert into car (make, model, price) values ('Ford', 'F150', 11647.61);
insert into car (make, model, price) values ('Porsche', '911', 8588.11);
insert into car (make, model, price) values ('Infiniti', 'G', 6460.79);
insert into car (make, model, price) values ('Porsche', '911', 13967.23);
insert into car (make, model, price) values ('Bentley', 'Continental', 14178.06);
insert into car (make, model, price) values ('Daewoo', 'Lanos', 14152.98);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', 2746.92);
insert into car (make, model, price) values ('Suzuki', 'Kizashi', 10937.63);
insert into car (make, model, price) values ('Dodge', 'Caravan', 19127.79);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 15648.93);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 3296.21);
insert into car (make, model, price) values ('Ford', 'Ranger', 10285.65);
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass Cruiser', 7873.25);
insert into car (make, model, price) values ('Volkswagen', 'Passat', 6649.12);
insert into car (make, model, price) values ('Ford', 'Escort', 18959.18);
insert into car (make, model, price) values ('Lexus', 'RX', 9948.61);
insert into car (make, model, price) values ('Hyundai', 'Scoupe', 10606.88);
insert into car (make, model, price) values ('Honda', 'Element', 11683.36);
insert into car (make, model, price) values ('Toyota', '4Runner', 10637.41);
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', 19588.77);
insert into car (make, model, price) values ('Suzuki', 'SJ', 18241.45);
insert into car (make, model, price) values ('Chrysler', 'Pacifica', 9286.48);
insert into car (make, model, price) values ('Volkswagen', 'rio', 19960.22);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 7990.92);
insert into car (make, model, price) values ('Nissan', 'Maxima', 8104.35);
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', 11255.64);
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', 5499.48);
insert into car (make, model, price) values ('Cadillac', 'Eldorado', 3596.9);
insert into car (make, model, price) values ('Subaru', 'Impreza', 12034.21);
insert into car (make, model, price) values ('Mazda', 'CX-7', 10936.34);
insert into car (make, model, price) values ('MINI', 'MINI', 11304.7);
insert into car (make, model, price) values ('Chrysler', '300M', 17142.9);
insert into car (make, model, price) values ('Nissan', '350Z', 17342.5);
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', 14982.55);
insert into car (make, model, price) values ('Subaru', 'Justy', 18427.51);
insert into car (make, model, price) values ('Toyota', 'Previa', 3211.2);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 2218.52);
insert into car (make, model, price) values ('Mitsubishi', 'Outlander', 13439.01);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 13911.34);
insert into car (make, model, price) values ('Toyota', 'Yaris', 15424.78);
insert into car (make, model, price) values ('Nissan', 'Frontier', 16221.51);
insert into car (make, model, price) values ('BMW', '7 Series', 10947.61);
insert into car (make, model, price) values ('GMC', 'EV1', 6022.35);
insert into car (make, model, price) values ('Ford', 'F150', 13522.49);
insert into car (make, model, price) values ('Buick', 'Skylark', 16346.07);
insert into car (make, model, price) values ('Isuzu', 'Ascender', 8878.33);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 5488.37);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 2500', 13956.32);
insert into car (make, model, price) values ('Saturn', 'Relay', 11786.83);
insert into car (make, model, price) values ('Kia', 'Sportage', 3783.64);
insert into car (make, model, price) values ('Honda', 'CR-X', 13680.05);
insert into car (make, model, price) values ('Suzuki', 'X-90', 14817.0);
insert into car (make, model, price) values ('Ford', 'Mustang', 19689.34);
insert into car (make, model, price) values ('Isuzu', 'Trooper', 8032.9);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 8604.59);
insert into car (make, model, price) values ('Honda', 'Odyssey', 15468.51);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 2260.02);
insert into car (make, model, price) values ('Mazda', 'B-Series', 2959.71);
insert into car (make, model, price) values ('Subaru', 'Leone', 17143.03);
insert into car (make, model, price) values ('Land Rover', 'Defender', 10598.68);
insert into car (make, model, price) values ('Nissan', 'Sentra', 7114.17);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 3333.87);
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', 17659.35);
insert into car (make, model, price) values ('Ford', 'E350', 12413.04);
insert into car (make, model, price) values ('Nissan', 'Armada', 2148.5);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 17555.31);
insert into car (make, model, price) values ('Lexus', 'LS', 14466.39);
insert into car (make, model, price) values ('Suzuki', 'Daewoo Lacetti', 3751.87);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 3212.15);
insert into car (make, model, price) values ('GMC', 'Yukon', 2399.28);
insert into car (make, model, price) values ('Audi', 'TT', 19886.48);
insert into car (make, model, price) values ('Pontiac', 'Firebird Formula', 4112.75);
insert into car (make, model, price) values ('Saab', '9-3', 5755.05);
insert into car (make, model, price) values ('Scion', 'tC', 6556.58);
insert into car (make, model, price) values ('Lotus', 'Elise', 6625.24);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 17904.06);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 11491.49);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLS AMG', 5475.13);
insert into car (make, model, price) values ('Ford', 'F-Series', 9081.28);
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B250', 7007.4);
insert into car (make, model, price) values ('Ford', 'Windstar', 12500.49);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 4964.87);
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', 10750.15);
insert into car (make, model, price) values ('Bentley', 'Mulsanne', 14742.28);
insert into car (make, model, price) values ('Infiniti', 'G', 7032.2);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 12117.59);
insert into car (make, model, price) values ('Buick', 'LaCrosse', 13843.16);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 11625.38);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 7331.58);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 10636.79);
insert into car (make, model, price) values ('Ford', 'E-Series', 15183.29);
insert into car (make, model, price) values ('Honda', 'S2000', 11775.08);
insert into car (make, model, price) values ('Mercedes-Benz', 'R-Class', 14640.09);
insert into car (make, model, price) values ('Mazda', 'MX-3', 14882.26);
insert into car (make, model, price) values ('Volkswagen', 'Corrado', 19615.57);
insert into car (make, model, price) values ('Pontiac', 'Safari', 13951.48);
insert into car (make, model, price) values ('Porsche', '911', 3272.76);
insert into car (make, model, price) values ('GMC', 'Sonoma', 15011.4);
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', 3901.48);
insert into car (make, model, price) values ('Plymouth', 'Acclaim', 17672.91);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 5459.37);
insert into car (make, model, price) values ('Porsche', '944', 5813.47);
insert into car (make, model, price) values ('Nissan', 'Sentra', 7245.17);
insert into car (make, model, price) values ('Volvo', 'S40', 2134.98);
insert into car (make, model, price) values ('Chevrolet', '3500', 11079.05);
insert into car (make, model, price) values ('Oldsmobile', '88', 2983.04);
insert into car (make, model, price) values ('Dodge', 'Durango', 6488.28);
insert into car (make, model, price) values ('Dodge', 'Daytona', 5694.92);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', 7714.57);
insert into car (make, model, price) values ('Honda', 'Odyssey', 16112.17);
insert into car (make, model, price) values ('Mazda', 'RX-8', 2363.83);
insert into car (make, model, price) values ('Aston Martin', 'Vanquish S', 7640.98);
insert into car (make, model, price) values ('BMW', '1 Series', 3602.88);
insert into car (make, model, price) values ('Saab', '900', 13586.25);
insert into car (make, model, price) values ('Lexus', 'IS', 11474.78);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 18651.81);
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', 18163.96);
insert into car (make, model, price) values ('Infiniti', 'G37', 15235.85);
insert into car (make, model, price) values ('GMC', 'Canyon', 10044.04);
insert into car (make, model, price) values ('Honda', 'CR-V', 14157.53);
insert into car (make, model, price) values ('Chevrolet', 'Caprice', 8049.92);
insert into car (make, model, price) values ('Mercedes-Benz', 'G55 AMG', 7147.51);
insert into car (make, model, price) values ('Ford', 'F-Series', 2464.32);
insert into car (make, model, price) values ('Mercury', 'Tracer', 13671.01);
insert into car (make, model, price) values ('GMC', '3500', 8032.2);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 11074.43);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 10172.3);
insert into car (make, model, price) values ('Buick', 'Century', 17451.1);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 18820.4);
insert into car (make, model, price) values ('Nissan', 'Sentra', 6423.43);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 16605.8);
insert into car (make, model, price) values ('Ford', 'Expedition EL', 13829.04);
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', 4407.68);
insert into car (make, model, price) values ('Jaguar', 'XK Series', 9137.5);
insert into car (make, model, price) values ('Saab', '9-5', 13596.37);
insert into car (make, model, price) values ('Ford', 'Bronco', 5743.5);
insert into car (make, model, price) values ('Mercury', 'Topaz', 14855.72);
insert into car (make, model, price) values ('Land Rover', 'LR2', 15470.88);
insert into car (make, model, price) values ('Toyota', 'Prius', 19171.23);
insert into car (make, model, price) values ('Buick', 'Century', 14956.05);
insert into car (make, model, price) values ('Volkswagen', 'Routan', 19792.67);
insert into car (make, model, price) values ('Ford', 'Five Hundred', 15815.69);
insert into car (make, model, price) values ('Toyota', 'Camry', 8045.11);
insert into car (make, model, price) values ('Buick', 'Park Avenue', 18759.86);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 15487.76);
insert into car (make, model, price) values ('Ford', 'Mustang', 16481.99);
insert into car (make, model, price) values ('Ford', 'Club Wagon', 9905.59);
insert into car (make, model, price) values ('Ferrari', '458 Italia', 16470.2);
insert into car (make, model, price) values ('Nissan', 'Xterra', 17801.15);
insert into car (make, model, price) values ('BMW', '760', 9507.43);
insert into car (make, model, price) values ('Pontiac', 'Fiero', 18558.05);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 19063.69);
insert into car (make, model, price) values ('Ram', '1500', 2177.28);
insert into car (make, model, price) values ('Mazda', 'MX-5', 2907.56);
insert into car (make, model, price) values ('Toyota', 'T100', 11841.55);
insert into car (make, model, price) values ('Nissan', 'Rogue', 12574.0);
insert into car (make, model, price) values ('Maserati', 'Biturbo', 12977.99);
insert into car (make, model, price) values ('Volkswagen', 'Golf', 6910.08);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 17996.68);
insert into car (make, model, price) values ('Kia', 'Sephia', 6504.4);
insert into car (make, model, price) values ('Oldsmobile', '98', 19199.14);
insert into car (make, model, price) values ('Ford', 'Explorer', 15125.33);
insert into car (make, model, price) values ('Nissan', '300ZX', 8328.24);
insert into car (make, model, price) values ('Chevrolet', 'Caprice', 11898.83);
insert into car (make, model, price) values ('Land Rover', 'Discovery', 6452.44);
insert into car (make, model, price) values ('Acura', 'RSX', 5097.07);
insert into car (make, model, price) values ('Mercedes-Benz', '400E', 19592.76);
insert into car (make, model, price) values ('Nissan', 'Armada', 15411.82);
insert into car (make, model, price) values ('Oldsmobile', '88', 13349.56);
insert into car (make, model, price) values ('Toyota', 'Tundra', 11945.78);
insert into car (make, model, price) values ('Pontiac', '6000', 4205.91);
insert into car (make, model, price) values ('Jeep', 'Liberty', 8811.14);
insert into car (make, model, price) values ('Toyota', '4Runner', 7424.36);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 8894.28);
insert into car (make, model, price) values ('Cadillac', 'CTS', 6904.65);
insert into car (make, model, price) values ('Ford', 'Econoline E250', 3690.61);
insert into car (make, model, price) values ('Ford', 'F150', 2638.75);
insert into car (make, model, price) values ('Toyota', 'TundraMax', 5667.93);
insert into car (make, model, price) values ('Honda', 'Odyssey', 17321.15);
insert into car (make, model, price) values ('Jeep', 'Compass', 18069.3);
insert into car (make, model, price) values ('Porsche', 'Boxster', 3657.79);
insert into car (make, model, price) values ('Hyundai', 'Tiburon', 14027.55);
insert into car (make, model, price) values ('Mercury', 'Tracer', 16420.59);
insert into car (make, model, price) values ('Nissan', 'Pathfinder', 12350.41);
insert into car (make, model, price) values ('Nissan', 'GT-R', 12684.07);
insert into car (make, model, price) values ('Cadillac', 'CTS', 11338.64);
insert into car (make, model, price) values ('Buick', 'Regal', 17944.23);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 3201.93);
insert into car (make, model, price) values ('Ferrari', '430 Scuderia', 12282.29);
insert into car (make, model, price) values ('GMC', 'Yukon', 8097.65);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', 9563.91);
insert into car (make, model, price) values ('Volvo', '960', 19592.57);
insert into car (make, model, price) values ('Volkswagen', 'Jetta', 13380.58);
insert into car (make, model, price) values ('BMW', 'M3', 18581.74);
insert into car (make, model, price) values ('Smart', 'Fortwo', 2650.85);
insert into car (make, model, price) values ('Ford', 'Probe', 9323.14);
insert into car (make, model, price) values ('Audi', 'RS 4', 3852.96);
insert into car (make, model, price) values ('Toyota', 'Tundra', 12131.43);
insert into car (make, model, price) values ('Subaru', 'Legacy', 17876.69);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 19703.33);
insert into car (make, model, price) values ('Audi', 'V8', 9552.91);
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', 17289.44);
insert into car (make, model, price) values ('Ford', 'Probe', 12192.82);
insert into car (make, model, price) values ('Kia', 'Spectra', 17108.3);
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', 2242.38);
insert into car (make, model, price) values ('Chevrolet', 'Silverado', 17431.44);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 8587.4);
insert into car (make, model, price) values ('Lotus', 'Elise', 12132.5);
insert into car (make, model, price) values ('Audi', 'Q7', 13039.37);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 12644.08);
insert into car (make, model, price) values ('Toyota', 'Tundra', 2879.57);
insert into car (make, model, price) values ('Mercury', 'Cougar', 18642.54);
insert into car (make, model, price) values ('Toyota', 'Avalon', 12796.2);
insert into car (make, model, price) values ('Mazda', 'GLC', 6053.95);
insert into car (make, model, price) values ('Land Rover', 'Defender', 15765.89);
insert into car (make, model, price) values ('Nissan', 'Maxima', 3381.95);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 13829.2);
insert into car (make, model, price) values ('Toyota', 'Highlander', 11563.08);
insert into car (make, model, price) values ('Suzuki', 'Esteem', 19092.09);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 6899.64);
insert into car (make, model, price) values ('Ford', 'Taurus', 10925.56);
insert into car (make, model, price) values ('Dodge', 'Viper', 8348.78);
insert into car (make, model, price) values ('Infiniti', 'Q', 16223.31);
insert into car (make, model, price) values ('Nissan', 'NX', 18443.36);
insert into car (make, model, price) values ('Audi', 'RS 6', 16224.51);
insert into car (make, model, price) values ('Ferrari', 'FF', 14298.75);
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', 6305.45);
insert into car (make, model, price) values ('Chevrolet', 'Tracker', 2689.29);
insert into car (make, model, price) values ('Mazda', 'Mazda6', 4359.99);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 15878.04);
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', 18178.55);
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', 10812.59);
insert into car (make, model, price) values ('Volvo', 'V50', 17687.19);
insert into car (make, model, price) values ('Porsche', 'Boxster', 19251.75);
insert into car (make, model, price) values ('GMC', 'Vandura 3500', 19322.23);
insert into car (make, model, price) values ('Buick', 'Skylark', 14827.46);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', 5977.61);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 6316.2);
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', 2337.61);
insert into car (make, model, price) values ('Saturn', 'Sky', 15409.96);
insert into car (make, model, price) values ('Pontiac', '6000', 11514.79);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 15899.71);
insert into car (make, model, price) values ('GMC', 'Sonoma', 5538.11);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 12143.4);
insert into car (make, model, price) values ('Infiniti', 'EX', 8347.86);
insert into car (make, model, price) values ('Chevrolet', 'Lumina', 18925.77);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 19888.88);
insert into car (make, model, price) values ('Lamborghini', 'Countach', 9644.65);
insert into car (make, model, price) values ('Volvo', 'XC90', 16704.82);
insert into car (make, model, price) values ('Honda', 'CR-V', 13980.57);
insert into car (make, model, price) values ('Pontiac', 'Sunbird', 19329.27);
insert into car (make, model, price) values ('Jeep', 'Cherokee', 9248.41);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 18580.41);
insert into car (make, model, price) values ('Mercedes-Benz', '500E', 11841.48);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 15838.74);
insert into car (make, model, price) values ('Dodge', 'Neon', 13410.48);
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', 17692.58);
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', 15961.13);
